name: silence_flutter_study
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  transparent_image: ^0.1.0
  cached_network_image: ^2.0.0
  dio: ^2.1.3
  cookie_jar: ^1.0.0
  shared_preferences: ^0.4.1
  banner: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/splash_bg.png
